import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TestNavbar } from "@/components/TestNavbar";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      <div className="">
      <TestNavbar />
      </div>
      <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
